### ISSUE TITLE
Provide documentation how to build and deploy web application in a Docker container

### ISSUE THREAD

**Issue by synergiator** [web-ridge/create-react-native-web-application#10]
It's not quite clear what is required to build and run the web app produced by this awesome generator tool.

If I follow the quick start tutorial in the README, ``` yarn web:build``` says, there is no such directory.

UPD. Replacing the yarn with an up-to-date one helps, still there are many missing dependencies. A two-stage Dockerfile would help a lot.

**Comment by RichardLindhout** [comment]
It uses create-react-app there are tutorials but I have made a proof of concept for a freelance interview a while ago.

Dockerfile
```
FROM node:alpine as build

ENV REACT_APP_API_BASE_URL=http://localhost:8080

WORKDIR /

COPY package.json ./
COPY yarn.lock ./


RUN yarn install

COPY . .
RUN yarn run web:build

FROM nginx:stable-alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

```

Push this to e.g. dockerhub.com

and in your docker-compose.yml later on
```
version: "3"

services:
  frontend:
    image: richardlindhout/omoda-pos-frontend:latest
    restart: always
    expose:
      - 80
    ports:
      - "80:80"

```
